// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAacRwDDxvHaEzNuZoM5tVkEmj4c2BBoBo',
    appId: '1:784459665443:web:7c10cdede4f257631d6196',
    messagingSenderId: '784459665443',
    projectId: 'evently-youssef-ashraf',
    authDomain: 'evently-youssef-ashraf.firebaseapp.com',
    storageBucket: 'evently-youssef-ashraf.firebasestorage.app',
    measurementId: 'G-CS8P33WV5Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiBwRzwEV3OI6plVe3PYRjL94Lg31is1w',
    appId: '1:784459665443:android:bb5197fdcf8cc7cc1d6196',
    messagingSenderId: '784459665443',
    projectId: 'evently-youssef-ashraf',
    storageBucket: 'evently-youssef-ashraf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3mL164ACL9mXEPvtWxqlVHThjVi74ouk',
    appId: '1:784459665443:ios:bfbe1408b0900b2e1d6196',
    messagingSenderId: '784459665443',
    projectId: 'evently-youssef-ashraf',
    storageBucket: 'evently-youssef-ashraf.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3mL164ACL9mXEPvtWxqlVHThjVi74ouk',
    appId: '1:784459665443:ios:bfbe1408b0900b2e1d6196',
    messagingSenderId: '784459665443',
    projectId: 'evently-youssef-ashraf',
    storageBucket: 'evently-youssef-ashraf.firebasestorage.app',
    iosBundleId: 'com.example.islami',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAacRwDDxvHaEzNuZoM5tVkEmj4c2BBoBo',
    appId: '1:784459665443:web:4607009acb485ede1d6196',
    messagingSenderId: '784459665443',
    projectId: 'evently-youssef-ashraf',
    authDomain: 'evently-youssef-ashraf.firebaseapp.com',
    storageBucket: 'evently-youssef-ashraf.firebasestorage.app',
    measurementId: 'G-000F1MVEWB',
  );
}
